### ISSUE TITLE
Kubernetic windows not being able to retrieve resources except for Releases

### ISSUE THREAD

**Issue by cazzoo** [harbur/kubernetic#101]
Hello,
I was using previous version of kubernetic on windows to get all resources of my cluster. I was able to get all except Releases (only 1 or 2 of them).
Recently updated to latest version of kubernetic and I'm not able anymore to get any resources except Releases (I get them all now).

That is quite a big regression to me. I could not use it anymore.
Could you please get a look ?

**Comment by rschoch** [comment]
can confirm, doesnt work anymore after upgrading from 2.2 to 2.3. am on windows

**Comment by marcelhdl** [comment]
on mac also

**Comment by spiddy** [comment]
Can you provide some info about the kubernetes cluster? this is probably not client OS related, since there are reports on different OSes.

In order to support EKS the kubernetes client has changed.

The configuration on kubeconfig (redacted without credentials) can also help identify the issue

**Comment by marcelhdl** [comment]
which information do you need?

**Comment by marcelhdl** [comment]
With the command "kubectl get po -n somenamespace" I can see all the deployed pods for example. But within Kubernetic I can't see anything.

Im connected successfully:
![Bildschirmfoto 2019-07-16 um 07 51 32](https://user-images.githubusercontent.com/26901337/61269363-a962b300-a79e-11e9-8d3c-5814b38fc40a.png)

But the Overview stays empty:
![Bildschirmfoto 2019-07-16 um 07 51 46](https://user-images.githubusercontent.com/26901337/61269389-bd0e1980-a79e-11e9-934e-adddc00f3456.png)

My config looks like the following:
```yaml
apiVersion: v1
clusters:
  - cluster:
      certificate-authority: cert.pem
      server: 'someadress:someport'
    name: dev
contexts:
  - context:
      cluster: dev
      namespace: namespace
      user: email
    name: dev
current-context: dev
kind: Config
preferences: {}
users:
  - name: email
    user:
      auth-provider:
        config:
          client-id: kube
          client-secret: kube
          id-token: >-
            sometoken
          idp-issuer-url: 'identityadress'
          refresh-token: >-
            someothertoken
        name: oidc
```
