### ISSUE TITLE
OIDC authentication seems broken in 2.3.0

### ISSUE THREAD

**Issue by desaintmartin** [harbur/kubernetic#103]
After downloading the latest version 2.3.0, OIDC-based authentication no longer works.

```yaml
- name:xxx
  user:
    auth-provider:
      config:
        client-id: xxx
        client-secret: xxx
        id-token: xxx
        idp-issuer-url: https://xxx.com
        refresh-token: XXX
      name: oidc


```
