### ISSUE TITLE
Exec auth seems broken in 2.4.1

### ISSUE THREAD

**Issue by kuzaxak** [harbur/kubernetic#118]
I have token based `aws-iam-authenticator` config. 

```
users:
- name: k8s.aws.XXXXXXXX
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - --forward-session-name
      - -i
      - k8s.aws.XXXXXX
      - -r
      - arn:aws:iam::XXXXXXXXXXX:role/DeveloperAccountAccessRole
      command: aws-iam-authenticator
      env: null
```

When I try to connect to this cluster kubernetic shows me error:

```
Get https://k8s.aws.XXXXXXXX/version?timeout=32s: error executing access token command "aws-iam-authenticator XXXXX": err=exec: "aws-iam-authenticator": executable file not found in $PATH 
```

I have `aws-iam-authenticator` in `/usr/local/bin/` folder.
