### ISSUE TITLE
RBAC Group Permissions Issue

### ISSUE THREAD

**Issue by cazter** [harbur/kubernetic#170]
We've got the majority of K8S users in an RBAC group that has no permissions to Secrets. Users in this group lose access in Kubernetic to everything except Pod's & Node's, no Configuration (configmap, autoscalers), no networking (services, ingresses, endpoints), storage, etc.

To clarify, Kubernetic just spins when these users click on something like Services. However, they have full permission to these objects via cli, kubectl.

Kubernetic 2.8.1. AWS/EKS, Kubernetes 1.16.

```yaml
#dev role. copied from default "edit" role, minus secrets access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-role
rules:
- apiGroups:
  - ""
  resources:
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  - services/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - impersonate
- apiGroups:
  - ""
  resources:
  - pods
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - replicationcontrollers
  - replicationcontrollers/scale
  - services
  - services/proxy
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - deployments/rollback
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  - statefulsets/scale
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/rollback
  - deployments/scale
  - ingresses
  - networkpolicies
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - bindings
  - events
  - limitranges
  - namespaces/status
  - pods/log
  - pods/status
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  - daemonsets
  - deployments
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  - statefulsets/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - ingresses
  - networkpolicies
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/status
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/status
  verbs:
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - daemonsets/status
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - daemonsets/status
  verbs:
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets/status
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - replicasets/status
  verbs:
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers/status
  verbs:
  - get
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers/status
  verbs:
  - list
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers/status
  verbs:
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs/status
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - cronjobs/status
  verbs:
  - list
- apiGroups:
  - batch
  resources:
  - cronjobs/status
  verbs:
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - list
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets/status
  verbs:
  - get
- apiGroups:
  - extensions
  resources:
  - daemonsets/status
  verbs:
  - list
- apiGroups:
  - extensions
  resources:
  - daemonsets/status
  verbs:
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - extensions
  resources:
  - deployments/status
  verbs:
  - list
- apiGroups:
  - extensions
  resources:
  - deployments/status
  verbs:
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - get
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - list
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - watch
- apiGroups:
  - extensions
  resources:
  - replicasets/status
  verbs:
  - get
- apiGroups:
  - extensions
  resources:
  - replicasets/status
  verbs:
  - list
- apiGroups:
  - extensions
  resources:
  - replicasets/status
  verbs:
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets/status
  verbs:
  - get
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets/status
  verbs:
  - list
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets/status
  verbs:
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: dev-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dev-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: dev-group
```
