### ISSUE TITLE
Pod OutOfcpu status reported as Unknown in Kubernetic

### ISSUE THREAD

**Issue by osvaldolove** [harbur/kubernetic#171]
Pods that have a status of `OutOfcpu` as reported by kubectl are reporting as `Unknown` status in Kubernetic.

*Kubernetic*
![image](https://user-images.githubusercontent.com/3800572/86903712-a4adb200-c107-11ea-9650-acc8f910a8be.png)

*kubectl*
![image](https://user-images.githubusercontent.com/3800572/86903778-b68f5500-c107-11ea-9a02-b8e44ffb4f7f.png)

**Comment by dkapanidis** [comment]
hi,

can you provide a YAML example of the Pod with `OutOfcpu` status? Also is there an easy way to reproduce this state?

**Comment by dkapanidis** [comment]
From https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename I understand that this happens when there is a `nodeName` for node selection in the Pod:

e.g:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
  nodeName: kube-01
```

Is this your case?

**Comment by dkapanidis** [comment]
Also another potential error in the use case is `OutOfmemory`

**Comment by osvaldolove** [comment]
Hi,

We use `nodeSelector` but when describing the pod I can see the YAML has `nodeName` property populated in it. We have a use case where we scale nodes out with the Cluster Autoscaler and create K8s Jobs programmatically that run on just on these nodes.

I've only noticed this `OutOfcpu` status since I have placed a CPU request/limit on the jobs.

```yaml
      resources:
        limits:
          cpu: 250m
          memory: 150Mi
        requests:
          cpu: 250m
          memory: 150Mi
```

I don't think we should be getting `OutOfcpu` as the scheduler shouldn't try and run the pod if it doesn't have resource, but this is a K8s problem, not yours.
