### ISSUE TITLE
OIDC-based auth doesn't work

### ISSUE THREAD

**Issue by ashb** [harbur/kubernetic#25]
Hello.

We have our cluster set up to use OIDC-based auth (via Azure Active Directory) and it doesn't work with kubernetic.

My .kube/config is included below. If I use the `k8s-dev-master` context it works fine, but if I use the `k8s-dev-master-Ash.Berlin@domain` context I don't see any resources in Kubernetic – it doesn't give any errors, shows a green/connected blob, but just shows zeros everywhere in the sidebar.

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: REDACTED
  name: k8s-platform-master
contexts:
- context:
    cluster: k8s-dev-master
    user: k8s-dev-master-admin
  name: k8s-dev-master
- context:
    cluster: k8s-dev-master
    user: Ash.Berlin@domain-k8s-dev-master
  name: k8s-dev-master-Ash.Berlin@domain

current-context: k8s-dev-master-Ash.Berlin@domain
kind: Config
preferences: {}
users:
- name: Ash.Berlin@domain-k8s-dev-master
  user:
    auth-provider:
      config:
        client-id: REDACTED
        client-secret: REDACTED
        id-token: REDACTED-JWT-TOKEN
        idp-issuer-url: https://login.microsoftonline.com/REDACTED-UUID/v2.0
        refresh-token: REDACTED-NON-JWT-TOKEN
      name: oidc
- name: k8s-dev-master-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```
