### ISSUE TITLE
Added support for service port-forwarding with named ports

### ISSUE THREAD

**Issue by dkapanidis** [harbur/kubernetic#269]
Port forwarding with named ports instead of numerical ports is added.

Now if you have a Service that uses `targetPort` with the port name instead of the numerical port it will port-forward properly:

<img width="1106" alt="Screenshot 2020-11-19 at 13 45 41" src="https://user-images.githubusercontent.com/367397/99668132-9edcbb80-2a6d-11eb-94dc-03d30328e354.png">

## How to Reproduce

Create a Service as:

```
kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  selector:
    app: nginx
  type: ClusterIP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 'nginx:alpine'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
```

Go to Service > Nginx > Ports and do port forwarding.

Notice that the Service targetPort is `http` and not `80`.
