### ISSUE TITLE
Context names with plus 

### ISSUE THREAD

**Issue by dominch** [harbur/kubernetic#283]
My original kube config contains context names with plus signs, example:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: fake-ca-file
    server: https://1.2.3.4
  name: development
- cluster:
    insecure-skip-tls-verify: true
    server: https://5.6.7.8
  name: scratch
contexts:
- context:
    cluster: development
    namespace: frontend
    user: developer
  name: dev-frontend+foo
- context:
    cluster: development
    namespace: storage
    user: developer
  name: dev-storage+bar
- context:
    cluster: scratch
    namespace: default
    user: experimenter
  name: exp-scratch+baz
current-context: ""
kind: Config
preferences: {}
users:
- name: developer
  user:
    client-certificate: fake-cert-file
    client-key: fake-key-file
- name: experimenter
  user:
    password: some-password
    username: exp
```

This is unreadable for kubernetic, changing + to - makes it work again.
