### ISSUE TITLE
Use oauth2-proxy in web-version for teams

### ISSUE THREAD

**Issue by stepanselyuk** [harbur/kubernetic#384]
Hello,

how to use oauth2-proxy in front of Kubernetic? In general it's working as usually, but I cannot make "users" work, so all users just going to use admin local default account.

I added a few specific arguments to oauth2-proxy, so it should pass headers to kubernetic, like `X-Auth-Request-User`, `X-Auth-Request-Groups`, `X-Auth-Request-Email` and `X-Auth-Request-Preferred-Username`

https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview/

```
- '--pass-user-headers=true'
- '--reverse-proxy=true'
- '--set-authorization-header=true'
- '--set-xauthrequest=true'
```

but I'm unsure if the headers passed to Kubernetic, and if Kubernetic should react on those.

**Comment by stepanselyuk** [comment]
In the Kubernetic ingress I used these annotations:
```
annotations:
  nginx.ingress.kubernetes.io/auth-signin: 'https://$host/oauth2/start?rd=$escaped_request_uri'
  nginx.ingress.kubernetes.io/auth-url: 'https://$host/oauth2/auth'
  nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-groups, x-auth-request-email"
```
