### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by Xuyuanp** [harbur/kubernetic#40]
My `~/.kube/config`:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: <masters-lbs-ip>
  name: k8s-remote
contexts:
- context:
    cluster: k8s-remote
    user: k8s-remote-admin
  name: k8s-remote-admin@k8s-remote
current-context: k8s-remote-admin@k8s-remote
kind: Config
preferences: {}
users:
- name: k8s-remote-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

kubectl works well. Nothing appeared in this app.
![image](https://user-images.githubusercontent.com/2245664/37751004-e974025e-2dca-11e8-8da2-193c3ba373c2.png)

**Comment by josue** [comment]
**Current Version:** 2.0.14 💥 

Not working for me either on one particular connection but it does work on other connections. `kubectl` does work for that one particular connection that doesn't work though.

The application logs are not showing anything, but it was showing logs in the previous version (v0.8.0): `/Users/$USER/Library/Logs/Kubernetic/log.log`

**Comment by josue** [comment]
Nevermind, the issue stopped and now the connection works. But it would be great to have a log file with useful debug data.

**Comment by spiddy** [comment]
Great to hear it works fine now, do you know what happened in between?

As for the debug data we'll get them back soon, added separate issue to manage it

**Comment by Xuyuanp** [comment]
I found a way to make it work. Just set `insecure-skip-tls-verify: true` in config file.

**Comment by spiddy** [comment]
great you made it work. it's a bit strange though, shouldn't kubectl also fail when insecure is not set to true?

**Comment by Eronarn** [comment]
Also running into this issue of kubectl working when Kubernetic isn't. In my case, setting `insecure-skip-tls-verify` didn't set a difference. Perhaps it's related to our use of a wrapper script to authenticate:

```
  - name: kubernetes-dev
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        args: null
        command: ~/login.sh
        env: null
```
