### ISSUE TITLE
Crash if ca-cert is relative to the ~/.kube directory

### ISSUE THREAD

**Issue by tardyp** [harbur/kubernetic#53]
my ~/.kube/config looks like this

```
apiVersion: v1
clusters:
  - cluster:
      certificate-authority: ca.pem
```
kubernetic crashes at boot with file not found error.

If using full path, it works:
```
apiVersion: v1
clusters:
  - cluster:
      certificate-authority: /Users/<xxx>/.kube/ca.pem
```
