### ISSUE TITLE
Quotas specifications are broken

### ISSUE THREAD

**Issue by Kami-no** [harbur/kubernetic#54]
Specifications tab
```
Resource | Used | Hard | Capacity
-- | -- | -- | --
limits.cpu | 1500m | 0 | -
limits.memory | 768Mi | 1 | NaN%
requests.cpu | 1500m | 2 | NaN%
requests.memory | 768Mi | 3 | NaN%
```

View tab
```
spec:
  hard:
    limits.cpu: '4'
    limits.memory: 2Gi
    requests.cpu: '4'
    requests.memory: 2Gi
status:
  hard:
    limits.cpu: '4'
    limits.memory: 2Gi
    requests.cpu: '4'
    requests.memory: 2Gi
  used:
    limits.cpu: 1500m
    limits.memory: 768Mi
    requests.cpu: 1500m
    requests.memory: 768Mi
```

kubectl describe quota -n default
```
Name:            default
Namespace:       default
Resource         Used   Hard
--------         ----   ----
limits.cpu       1500m  4
limits.memory    768Mi  2Gi
requests.cpu     1500m  4
requests.memory  768Mi  2Gi
```
