### ISSUE TITLE
[Feature] EKS connectivity

### ISSUE THREAD

**Issue by cabrinoob** [harbur/kubernetic#57]
Hi,
I've just created an EKS cluster in Amazon. The problem is that Kubernetic does not seem to be compatible with the credentials specificity of EKS.

The authentication process uses an Heptio command to get a Token : 

Here is an extract of my kubeconfig file.

```
apiVersion: v1
kind: Config
clusters: {}
contexts: {}
preferences: {}
users:
  - name: aws
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        command: heptio-authenticator-aws
        args:
          - token
          - '-i'
          - my-eks-cluster
        env:
          - name: AWS_PROFILE
            value: eks-profile
```

But when I use it with kubernetic, nothing happens.

Do you plan to make it work with EKS cluster?

Thank you.
