### ISSUE TITLE
'azure' auth-provider not supported

### ISSUE THREAD

**Issue by mattparkes** [harbur/kubernetic#66]
I am using Kubernetes OIDC authentication, but specifically with Azure AD as an auth-provider as per https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/plugin/pkg/client/auth/azure/README.md

The users section of my kubeconfig file looks like this:
```
users:
- name: oidc
  user:
    auth-provider:
      config:
        access-token: REDACTED
        apiserver-id: REDACTED
        client-id: REDACTED
        expires-in: REDACTED
        expires-on: REDACTED
        refresh-token: REDACTED
        tenant-id: REDACTED
        environment: AzurePublicCloud
      name: azure
```

When I launch Kubernetic, all my clusters with `auth-proivder: name: azure` nothing works.

Tangentially related, but also think Kubernetic doesn't use the KUBECONFIG environment variable (`export  KUBECONFIG=$KUBECONFIG:config-demo:config-demo-2`) as per: https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#set-the-kubeconfig-environment-variable
